CREATE TABLE HOUSE(
       ID NUMBER(10)     
     , INOUT VARCHAR2(10) CHECK(INOUT IN('I', 'O'))
     , PRICE NUMBER(20)
     , BUY_DATE DATE
     , EXPENSE VARCHAR(10) NOT NULL
     , ETC VARCHAR(100)
     , CONSTRAINT HOUSE_PK PRIMARY KEY (ID)
     
);

DROP TABLE HOUSE;
