/*
테이블에 존재하는 데이터를 기반으로 데이터 삽입(INSERT)
*/
CREATE TABLE COMMISSION_LIST(
	   EMP_ID NUMBER
	 , EMP_NAME VARCHAR2(50)
	 , COMMISSION_PCT NUMBER(2, 2)
	 , DEPT_ID NUMBER
);

INSERT INTO COMMISSION_LIST(
     SELECT EMPLOYEE_ID
     	  , FIRST_NAME || ' ' || LAST_NAME
     	  , COMMISSION_PCT
     	  , DEPARTMENT_ID
       FROM EMPLOYEES
      WHERE COMMISSION_PCT IS NOT NULL
);

SELECT * FROM COMMISSION_LIST;

/*
 * INSERT ALL INTO
 * 		다른 테이블에 존재하는 데이터를 새로 생성한 테이블에 삽입하기 위한 구문
 * 		여러 테이블에 데이터 삽입할 수 있다.
 */
CREATE TABLE NO_COMMISSION_LIST(
	   EMP_ID NUMBER
	 , EMP_NAME VARCHAR2(50)
	 , SALARY NUMBER
	 , DEPT_ID NUMBER
);

INSERT ALL
    WHEN COMMISSION_PCT IS NOT NULL THEN 
        INTO COMMISSION_LIST VALUES(EMP_ID, EMP_NAME, COMMISSION_PCT, DEPT_ID)
    WHEN COMMISSION_PCT IS NULL THEN
		INTO NO_COMMISSION_LIST VALUES(EMP_ID, EMP_NAME, SALARY, DEPT_ID)
SELECT EMPLOYEE_ID AS EMP_ID
     , FIRST_NAME || ' ' || LAST_NAME AS EMP_NAME
     , COMMISSION_PCT
     , SALARY
     , DEPARTMENT_ID AS DEPT_ID
  FROM EMPLOYEES;

SELECT * FROM COMMISSION_LIST;
SELECT * FROM NO_COMMISSION_LIST;
 