SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 210;

-- 이름 : john

SELECT * 
  FROM EMPLOYEES
 WHERE LOWER(FIRST_NAME) LIKE '%john%'
    OR LOWER(LAST_NAME) LIKE '%john%';
    