/*
 * FUNCTION 객체
 *     - PL/SQL 구문을 사용하여 생성할 수 있는 객체
 *     - 프로시져와 유사하며, 일반 프로그래밍 언어의 함수와 같이 값을 리턴(반환) 한다.
 *     - FUNCTION 은 PROCEDURE 와 다르게 SQL 구문 안에서 사용할 수 있다.
 */

CREATE OR REPLACE FUNCTION FUN_SAMPLE1(
       NUM1 NUMBER
     , NUM2 NUMBER
) RETURN NUMBER
IS
BEGIN
    RETURN NUM1 + NUM2;
END;

SELECT FUN_SAMPLE1(10, 20) FROM DUAL;


CREATE OR REPLACE FUNCTION GET_JOB_TITLE(
       F_JOB_ID VARCHAR2
) RETURN VARCHAR2
IS
    VAR_JOB_TITLE VARCHAR(35);
BEGIN
    SELECT JOB_TITLE INTO VAR_JOB_TITLE FROM JOBS WHERE JOB_ID = F_JOB_ID;
    RETURN VAR_JOB_TITLE;
END;

SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , JOB_ID
     , GET_JOB_TITLE(JOB_ID)
  FROM EMPLOYEES;

SELECT * FROM USER_ERRORS;




